[build-system]
build-backend = "flit_core.buildapi"
requires = ["flit_core >=3.2,<4"]

[project]
authors = [{name = "Graziella", email = "graziella@lumache"}]
dynamic = ["version", "description"]
name = "fastpandas"
